### ISSUE TITLE
Assertion Error on Timer

### ISSUE THREAD

**Issue by BayoKwendo** [rbrahul/deno_cron#4]
I am getting this error at intervals. the error seem to come from clearInterval Function on driver.
`Any lead in resolving it permanently? Thanks

```error: Uncaught (in promise) AssertionError: Assertion failed.
    at assert (deno:ext/timers/01_timers.js:40:13)
    at setGlobalTimeout (deno:ext/timers/01_timers.js:349:5)
    at setOrClearGlobalTimeout (deno:ext/timers/01_timers.js:393:7)
    at unschedule (deno:ext/timers/01_timers.js:442:9)
    at clearTimer (deno:ext/timers/01_timers.js:564:5)
    at clearInterval (deno:ext/timers/01_timers.js:581:5)
    at https://deno.land/x/deno_cron@v1.0.0/cron.ts:118:13
    at fire (deno:ext/timers/01_timers.js:477:7)
    at handleTimerMacrotask (deno:ext/timers/01_timers.js:338:7)
Watcher Process finished. Restarting on file change...```

**Comment by Hexagon** [comment]
Meanwhile - try out [croner](https://github.com/hexagon/croner) which is a well maintained alternative
